name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    services:
      mssql:
        image: mcr.microsoft.com/mssql/server:2019-latest
        env:
          SA_PASSWORD: 'rnc'
          ACCEPT_EULA: 'Y'
        ports:
          - 1433:1433
        options: --health-cmd "wait-for-it -t 60 localhost:1433"

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install PyQt5

      - name: MS SQL stuff
        run: |
          /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P $SA_PASSWORD -Q "SELECT 1"

        name: Run tests
        run: |
          pytest